# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RapidCompose < Formula
  desc ""
  homepage ""
  version "1.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/trusz/rapid-compose/releases/download/v1.6.2/rapid-compose_1.6.2_Darwin_arm64.tar.gz"
      sha256 "a458718cb03bb3cfd86caa4c8d4c2457d57c01a1e8fe6f99b662a86a92af26f5"

      def install
        bin.install "rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/trusz/rapid-compose/releases/download/v1.6.2/rapid-compose_1.6.2_Darwin_x86_64.tar.gz"
      sha256 "39ed94f35e5e7af7dae904063a0f647f4c70382321f645431b16f8a8ee905eaf"

      def install
        bin.install "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trusz/rapid-compose/releases/download/v1.6.2/rapid-compose_1.6.2_Linux_arm64.tar.gz"
      sha256 "025cfa51fcffd51c5bb496ad5aed0ea06f3432cab335ad712ba69cf2a85b50ad"

      def install
        bin.install "rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/trusz/rapid-compose/releases/download/v1.6.2/rapid-compose_1.6.2_Linux_x86_64.tar.gz"
      sha256 "65a56d870c177ba7f828d15697acf6c45a794094b1fdfd871863a3d6348f47a7"

      def install
        bin.install "rc"
      end
    end
  end
end
